---
abstract: 'see http://xkcd.com/936/'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Crypt::XkcdPassword
name: Crypt-XkcdPassword
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Module::Runtime: 0
  Moo: 0
  Role::Commons::Authority: 0
  Types::Standard: 0
  match::simple: 0
  perl: 5.10.1
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Crypt-XkcdPassword
  homepage: https://metacpan.org/release/Crypt-XkcdPassword
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-crypt-xkcdpassword
version: 0.005
x_contributors:
  - Nobody
  - TOBYINK
